### PR TITLE
new version

### PR DESCRIPTION
**Pull request by Kyoudou**
was trying to upload, but couldnt log into your account !?

This is my account and apparently I somehow created a fork when trying to add the new file.

### CODE REVIEW

**Comment by Idrinth** [comment]
the file is named differently, assuming you don't want to have a file next to the original, that is not a good idea. you might want to update the original instead.

**Comment by Idrinth** [comment]
regarding the fork, tht's normal behaviour, you lack the rights to commit in here because your account wasn't added as a contributor.

**Comment by Kyoudou** [comment]
I didnt find a rename button >_> but it should be the right name now. ...I hope...

**Comment by Idrinth** [comment]
@Kyoudou I'm just reworking this so editing is easier again - will fork this later and check, the file it's just too big with all those embedded images :/

**Comment by Idrinth** [comment]
I think you broke it, @Kyoudou - will close this pull request for now :)

**Pull request closed without merging**
